Structure of PSF section
CosmoStat/Shear-and-PSF-Reading-Group pull request #37
Opened 2021-03-26 10:53 UTC by sfarrens

Added structured to PSF section discussed in #32, #33 and #34

2021-03-26 15:01 UTC, thuiop requested changes
The PR seems OK, I only found one minor typo !

2021-03-26 15:01 UTC, thuiop commented on shearbook/psf/star-selection.md
> +How to identify the stallar locus with emphasis on the purity of the sample.
```suggestion
How to identify the stellar locus with emphasis on the purity of the sample.
```

2021-03-26 16:24 UTC, sfarrens commented
Thanks @thuiop, I have added you to the repo so you can now be assigned issues etc.

If you are happy with this now please go to "Files changed" -> "Review changes" -> "Approve" so that I can merge. 🙂

2021-03-26 23:03 UTC, thuiop approved these changes

2021-04-02 13:04 UTC, andrevitorelli approved these changes

2021-04-02 13:04 UTC, merged